                     ***    1 variantas *   6 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.9 m, l2=4.2 m, l3=2.4 m, a=0.5 m ir b=1.4 m bei apkrovos
      F=55 kN, M=40 kN.m ir p=25 kN/m.
                     ***    2 variantas *  11 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.4 m, l2=3.8 m, l3=2.1 m, a=1.4 m ir b=0.7 m bei apkrovos
      F=35 kN, M=35 kN.m ir p=16 kN/m.
                     ***    3 variantas *  16 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.2 m, l2=3.4 m, l3=2.5 m, a=0.4 m ir b=1.8 m bei apkrovos
      F=55 kN, M=35 kN.m ir p=11 kN/m.
                     ***    4 variantas *  21 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.8 m, l2=5.6 m, a=1.2 m ir b=1.2 m bei apkrovos
      F=35 kN, M=55 kN.m ir p=18 kN/m.
                     ***    5 variantas *  26 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.6 m, l2=4.0 m, l3=2.5 m, a=0.5 m ir b=1.3 m bei apkrovos
      F=45 kN, M=35 kN.m ir p=14 kN/m.
                     ***    6 variantas *  31 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.2 m, l2=4.3 m, l3=2.6 m, a=0.6 m ir b=0.9 m bei apkrovos
      F=65 kN, M=30 kN.m ir p=12 kN/m.
                     ***    7 variantas *   3 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.6 m, l2=3.7 m, l3=2.6 m, a=1.1 m ir b=1.2 m bei apkrovos
      F=40 kN, M=45 kN.m ir p=27 kN/m.
                     ***    8 variantas *   8 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=5.0 m, l2=3.2 m, l3=3.5 m, a=0.5 m ir b=0.4 m bei apkrovos
      F=30 kN, M=60 kN.m ir p=22 kN/m.
                     ***    9 variantas *  13 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.0 m, l2=4.8 m, a=1.0 m ir b=1.5 m bei apkrovos
      F=70 kN, M=25 kN.m ir p=15 kN/m.
                     ***   10 variantas *  18 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.5 m, l2=3.8 m, l3=3.0 m, a=1.5 m ir b=1.1 m bei apkrovos
      F=60 kN, M=45 kN.m ir p=18 kN/m.
                     ***   11 variantas *  23 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.1 m, l2=4.5 m, l3=2.7 m, a=0.7 m ir b=0.8 m bei apkrovos
      F=50 kN, M=20 kN.m ir p=17 kN/m.
                     ***   12 variantas *  28 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.9 m, l2=4.0 m, l3=2.1 m, a=0.6 m ir b=0.7 m bei apkrovos
      F=40 kN, M=15 kN.m ir p=25 kN/m.
                     ***   13 variantas *  33 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.7 m, l2=4.2 m, l3=2.6 m, a=0.8 m ir b=0.6 m bei apkrovos
      F=30 kN, M=50 kN.m ir p=14 kN/m.
                     ***   14 variantas *   5 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.0 m, l2=5.0 m, a=0.7 m ir b=1.0 m bei apkrovos
      F=35 kN, M=55 kN.m ir p=10 kN/m.
                     ***   15 variantas *  10 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.7 m, l2=3.9 m, l3=2.9 m, a=1.0 m ir b=0.8 m bei apkrovos
      F=45 kN, M=25 kN.m ir p=23 kN/m.
                     ***   16 variantas *  15 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=5.1 m, l2=4.1 m, l3=2.1 m, a=1.2 m ir b=1.4 m bei apkrovos
      F=65 kN, M=10 kN.m ir p=16 kN/m.
                     ***   17 variantas *  20 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.1 m, l2=3.6 m, a=0.7 m ir b=0.4 m bei apkrovos
      F=45 kN, M=35 kN.m ir p=25 kN/m.
                     ***   18 variantas *  25 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.6 m, l2=3.5 m, a=1.1 m ir b=1.4 m bei apkrovos
      F=35 kN, M=40 kN.m ir p=18 kN/m.
                     ***   19 variantas *  30 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.0 m, l2=5.2 m, a=2.0 m ir b=0.7 m bei apkrovos
      F=55 kN, M=35 kN.m ir p=15 kN/m.
                     ***   20 variantas *   2 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.9 m, l2=4.0 m, a=1.8 m ir b=1.8 m bei apkrovos
      F=65 kN, M=35 kN.m ir p=19 kN/m.
                     ***   21 variantas *   7 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.4 m, l2=4.2 m, l3=2.5 m, a=0.5 m ir b=1.2 m bei apkrovos
      F=55 kN, M=55 kN.m ir p=25 kN/m.
                     ***   22 variantas *  12 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.2 m, l2=3.8 m, a=1.4 m ir b=1.3 m bei apkrovos
      F=35 kN, M=35 kN.m ir p=16 kN/m.
                     ***   23 variantas *  17 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.8 m, l2=3.4 m, a=0.4 m ir b=0.9 m bei apkrovos
      F=55 kN, M=30 kN.m ir p=11 kN/m.
                     ***   24 variantas *  22 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.6 m, l2=5.6 m, a=1.2 m ir b=1.2 m bei apkrovos
      F=35 kN, M=45 kN.m ir p=18 kN/m.
                     ***   25 variantas *  27 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.2 m, l2=4.0 m, l3=2.6 m, a=0.5 m ir b=0.4 m bei apkrovos
      F=45 kN, M=60 kN.m ir p=14 kN/m.
                     ***   26 variantas *  32 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.6 m, l2=4.3 m, a=0.6 m ir b=1.5 m bei apkrovos
      F=65 kN, M=25 kN.m ir p=12 kN/m.
                     ***   27 variantas *   4 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=5.0 m, l2=3.7 m, l3=2.3 m, a=1.1 m ir b=1.1 m bei apkrovos
      F=40 kN, M=45 kN.m ir p=27 kN/m.
                     ***   28 variantas *   9 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.0 m, l2=3.2 m, a=0.5 m ir b=0.8 m bei apkrovos
      F=30 kN, M=20 kN.m ir p=22 kN/m.
                     ***   29 variantas *  14 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.5 m, l2=4.8 m, l3=2.7 m, a=1.0 m ir b=0.7 m bei apkrovos
      F=70 kN, M=15 kN.m ir p=15 kN/m.
                     ***   30 variantas *  19 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.1 m, l2=3.8 m, l3=2.1 m, a=1.5 m ir b=0.6 m bei apkrovos
      F=60 kN, M=50 kN.m ir p=18 kN/m.
                     ***   31 variantas *  24 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.9 m, l2=4.5 m, a=0.7 m ir b=1.0 m bei apkrovos
      F=50 kN, M=55 kN.m ir p=17 kN/m.
                     ***   32 variantas *  29 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.7 m, l2=4.0 m, l3=2.5 m, a=0.6 m ir b=0.8 m bei apkrovos
      F=40 kN, M=25 kN.m ir p=25 kN/m.
                     ***   33 variantas *   1 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=3.0 m, l2=4.2 m, l3=2.9 m, a=0.8 m ir b=1.4 m bei apkrovos
      F=30 kN, M=10 kN.m ir p=14 kN/m.
                     ***   34 variantas *   7 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=4.7 m, l2=5.0 m, l3=2.1 m, a=0.7 m ir b=0.4 m bei apkrovos
      F=35 kN, M=35 kN.m ir p=10 kN/m.
                     ***   35 variantas *  12 schema  ***
      Rasti konstrukcineje schemoje nurodytos sijos nezinomus atraminius
      momentus, nubraizyti irazu diagramas bei parinkti sijos skerspjuvi
      (plieninis dvitejis, [S]=160 MPa), kai duota:
      l1=5.1 m, l2=3.9 m, a=1.0 m ir b=1.4 m bei apkrovos
      F=45 kN, M=40 kN.m ir p=23 kN/m.
